# Basic
title: è¿œå¿—
subtitle: ä¸ªäººç«™
description: æ¬¢è¿æ¥åˆ°æˆ‘çš„ä¸ªäººç«™~
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: Xiaowei
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: R / GSA
url: "https://xiaowei3223.github.io"

# Comment
comment:
    disqus: leopard
    # uyan: 2143225  # æœ‰è¨€id,ç™»å½•æœ‰è¨€å®˜ç½‘ç”³è¯·

# Social
social:
    #weibo: 5366874726 
    github: xiaowei3223
    # zhihu: panpanleopard
    # juejin: xxx
    #jianshu: 2ada30d8d0f7
    # twitter: 
    mail: h15016211223@163.com


# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
baidu:
    id: 8ba1c6be0953b6f9c2ba38e57f615421  

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
ga:
    #id: UA-84134159-3  
    #host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: Home

# Navigation buttons in the front page.s
nav:
    #- {title: Home, description: archive, url: '/archive'}   
    - {title: Tags, description: tags, url: '/tags'}      
    #- {title: æŠ€æœ¯æ”¯æŒ, description: support, url: '/support'}      
    - {title: about me, description: about, url: '/about'}   
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


